# Generated by Django 5.2 on 2025-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='profile_pictures/profile.jpg', upload_to='profile_pictures'),
        ),
    ]
