# Generated by Django 5.2 on 2025-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://plakarestaurant.ca/wp-content/themes/twentytwentythree-child/img/food-placeholder.png'),
        ),
    ]
